export const SET_PETS_LOADING = "SET_PETS_LOADING";

export const GET_PETS = "GET_PETS";
export const GET_PETS_SUCCESS = "GET_PETS_SUCCESS";
export const GET_PETS_FAIL = "GET_PETS_FAIL";

export const GET_DONATIONS = "GET_DONATIONS";
export const GET_DONATIONS_SUCCESS = "GET_DONATIONS_SUCCESS";
export const GET_DONATIONS_FAIL = "GET_DONATIONS_FAIL";
